### ISSUE TITLE
Duplication declaration with `preserve: true` and `strict: false`

### ISSUE THREAD

**Issue by le0pard** [postcss/postcss-custom-properties#109] opened 2018-04-04 15:52 UTC
Hello. Plugin add always duplicate declarations with options `preserve: true` and `strict: false`. Example:

```
         require('postcss-cssnext')({
            browsers: [
              'last 2 version'
            ],
            features: {
              rem: false,
              customProperties: {
                strict: false,
                warnings: false,
                preserve: true
              }
            }
          }),
```

Input:

```
.form-field__input
  width: 99%
  font-size: 1.8rem
  color: var(--emphColor)
  border-radius: 6px
  border: 1px solid var(--commentColor)
  background-color: color(var(--headsColor) tint(4%))
```

Output:

```
.form-field__input {
  width: 99%;
  font-size: 1.8rem;
  color: var(--emphColor);
  color: var(--emphColor);
  border-radius: 6px;
  border: 1px solid var(--commentColor);
  border: 1px solid var(--commentColor);
  background-color: color(var(--headsColor) tint(4%));
  background-color: color(var(--headsColor) tint(4%)); }
```

![123](https://user-images.githubusercontent.com/98444/38318883-c0846922-3830-11e8-9534-083ef3b93ff9.png)

Looks like it still trying to add fallback. Is it possible to disable such behaviour of plugin?

postcss-custom-properties version 6.2.0

**Comment by oleersoy** [comment] 2018-05-03 04:38
I'm seeing something similar to this.  For example with this as the input:

``` css
.u-font-family-ampersand {
    font-family: var(--font-family-ampersand) !important;
```

This is the output:

``` css
.u-font-family-ampersand {
    font-family: Ampersand,ff-more-web-pro,"More Pro",Georgia,Times,serif !important;
    font-family: var(--font-family-ampersand) !important;
```

I'm expecting only:
``` css
.u-font-family-ampersand {
    font-family: Ampersand,ff-more-web-pro,"More Pro",Georgia,Times,serif !important;
```

**Comment by oleersoy** [comment] 2018-05-03 14:52
Any thoughts on what version we can revert to while this is sorted out?

**Comment by jonathantneal** [comment] 2018-05-04 12:40
I’ll look into creating a test for this. Once verified, that will help me with a resolution. You can see the different tests I have made here, if anyone feels up to contributing one today:

https://github.com/jonathantneal/postcss-tests

**Comment by cfrank-rv** [comment] 2018-05-04 13:36
This issue is probably caused by something else since the test I ran show postcss-custom-properties returning the correct results using the settings in the OP.

https://github.com/cfrank-rv/postcss-tests/tree/master/postcss-custom-properties-test-01

I ran the test on `6.3.1` which is where I was seeing the error.

**Comment by jonathantneal** [comment] 2018-05-07 03:25
Okay, let me know if you discover an issue with this plugin, as that would help me write a fix. If your test shows the plugin operating correctly and we haven’t had anything further to debug, next weekend I will close this issue.

**Comment by pldg** [comment] 2018-05-09 07:36
I had the same problem with `v7.0.0`.
I'm using Webpack 4 with postcss-loader.

Adding [postcss-import](https://github.com/postcss/postcss-import) as first plugin in the list solve the problem.

**Comment by le0pard** [comment] 2018-05-09 07:44
@pldg I have exactly this issue, where `postcss-import` is first and `postcss-custom-properties@7.0.0`:

```js
{
    loader: 'postcss-loader',
    options: {
      sourceMap: true,
      plugins: function() {
        return [
          require('postcss-import')({
            addDependencyTo: webpack
          }),
          require('postcss-url')(),
          require('lost')({
            flexbox: 'flex'
          }),
          require('rucksack-css')(),
          require('postcss-cssnext')({
            browsers: [
              'last 2 version'
            ],
            features: {
              rem: false,
              customProperties: {
                strict: false,
                warnings: false,
                preserve: true
              }
            }
          }),
          require('postcss-browser-reporter')(),
          require('postcss-reporter')()
        ];
      }
    }
  }
```

**Comment by pldg** [comment] 2018-05-09 09:29
@le0pard  

`addDependencyTo`, what's this option? It's not even in [postcss-import options list](https://github.com/postcss/postcss-import#options).

Maybe the problem is *postcss-cssnext*?

Try *postcss-custom-properties* stand alone version.

My config:

```javascript
{
  loader: 'style-loader',
  options: {
    sourceMap: true
  }
},
{
  loader: 'css-loader',
  options: {
    sourceMap: true
  }
},
{
  loader: 'postcss-loader',
  options: {
    sourceMap: true,
    plugins: () => ([
      require('postcss-import'),
      require('postcss-custom-properties')({
        preserve: false
      }),
      require('autoprefixer')
    ])
  }
}
```

Also with `preserve: true` works fine.

**Comment by le0pard** [comment] 2018-05-09 09:34
@pldg `addDependencyTo` do nothing right now - no influence. cssnext just number of postcss packages - https://github.com/MoOx/postcss-cssnext/blob/master/package.json (including this one).

**Comment by pldg** [comment] 2018-05-26 16:42
As I said in the comment above, **adding `postcss-import` as first plugin solve the problem**.

I made a test repository [test-postcss-custom-properties](https://github.com/pldg/test-postcss-custom-properties) with 3 branches:

- [master](https://github.com/pldg/test-postcss-custom-properties/tree/master) branch is tested using Webpack 4 with `postcss-custom-properties`
- [test-with-cssnext](https://github.com/pldg/test-postcss-custom-properties/tree/test-with-cssnext) branch is tested using Webpack 4 with `postcss-cssnext`
- [without-webpack](https://github.com/pldg/test-postcss-custom-properties/tree/without-webpack) branch is tested using `postcss-cli` instead of Webpack

Anyway `postcss-custom-properties` should works also without `postcss-import` and this "duplication" bug should be fixed.

**Comment by le0pard** [comment] 2018-05-26 16:50
@pldg project with pistcss-import and this plugin - issue still present: https://github.com/le0pard/mpw.js

**Closed** 2018-09-16 20:50 UTC

**Comment by PFight** [comment] 2020-06-26 10:28
Still getting dublication on 9.1.1 using rollup:

    background: var(--checked-pin-color, #fff);

=>

    background: #fff;
    background: #fff;
    background: var(--checked-pin-color, #fff);
