### ISSUE TITLE
Remove :root in output file while preserve: false?

### ISSUE THREAD

**Issue by joe223** [postcss/postcss-custom-properties#160] opened 2018-12-14 12:57 UTC
```css
:root {
  /** something **/
  --color: red;
}

h1 {
  color: var(--color);
}

/* becomes */
:root {
  /** something **/
}
h1 {
  color: red;
}
```
Can we just remove `:root` when it contain comments?

**Comment by RoberMac** [comment] 2019-02-11 05:59
Same issue :)

**Comment by pascalduez** [comment] 2019-02-11 07:33
Dupe of #123

**Closed** 2019-02-11 07:57 UTC
