### ISSUE TITLE
fs import prevents in-browser usage

### ISSUE THREAD

**Issue by TheFirstAvenger** [postcss/postcss-custom-properties#143] opened 2018-09-27 19:04 UTC
Creating a browser feature where you type postcss in one textarea and it displays css in the other. This works for other processors such as autoprefixer, nested, hexrgba, and discard-comments, but fails with postcss-custom-properties due to the fs import calls in import and export.

**Comment by jonathantneal** [comment] 2018-10-02 18:00
If you are not using `fs`, can you redirect that import to something like an empty module?

**Comment by jonathantneal** [comment] 2018-10-02 18:15
Since this is not a bug with the module, but an implementation question, I am closing this issue — though we may continue the conversation.

**Closed by jonathantneal** 2018-10-02 18:15 UTC
